package com.pascal.habittracker.data.models

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.versionedparcelable.VersionedParcelize
import kotlinx.android.parcel.Parcelize

@Parcelize //make it possible to pass from one fragment to another
@Entity(tableName = "habit_table")//make table
data class Habit(
    @PrimaryKey(autoGenerate = true) //create autogenerated primary key
    val id:Int,
    val habitTittle:String,
    val habitDescription:String,
    val habitStartTime:String,
    val imageId:Int,
):Parcelable
